services:
    db:
        image: postgres:17.4
        restart: always
        environment:
            - POSTGRES_HOST=${DB_HOST}
            - POSTGRES_PORT=${DB_PORT}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - ${PGSQL_EXPOSED_PORT}:5432
        volumes:
            - pgsql_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "runuser", "-u", "postgres", "--", "pg_isready" ]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    pgsql_data:
        name: ${CONTAINER_NAME}
